name: OWASP ZAP Integration GitHub

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:          
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://ip172-18-0-16-chbb4081k7jg00fbrndg-80.direct.labs.play-with-docker.com/www/homepage.html'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'